[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
roulette_dapp = "9UiNkKquaH2AhXmQC7QKfrtyZoF3mHJzJcmYxvDdir3H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
